### ISSUE TITLE
Fatal error when acivating blocklist

### ISSUE THREAD

**Issue by frank4360** [CIDRAM/Docs#1] opened 2019-05-17 13:37 UTC
Fatal error: Uncaught TypeError: Argument 2 passed to {closure}() must be of the type array, string given, called in /homepages/*****Med-and-Mountain/CIDRAM/vault/frontend_functions.php on line 1974 and defined in /homepages/*****Med-and-Mountain/CIDRAM/vault/frontend_functions.php:723 Stack trace: #0 /homepages/*****Med-and-Mountain/CIDRAM/vault/frontend_functions.php(1974): {closure}('ipv4', 'BD_cidram.inc') #1 /homepages/*****Med-and-Mountain/CIDRAM/vault/frontend_functions.php(1578): {closure}('BD_cidram.inc') #2 /homepages/*****Med-and-Mountain/CIDRAM/vault/frontend.php(1500): {closure}('activate-compon...', 'BD_cidram.inc') #3 /homepages/*****Med-and-Mountain/CIDRAM/loader.php(102): require('/homepages/46/d...') #4 {main} thrown in /homepages/*****Med-and-Mountain/CIDRAM/vault/frontend_functions.php on line 723

**Trying to activate blocklist for Bangladesh IPv4.
Same for other blocklist, eg ChinaIPv4

Installs worked without a problem, but all Activates fail.**

**Comment by DanielRuf** [comment] 2019-05-17 14:02
Not related to docs but the frontend_functions.php file.

Also duplicate of https://github.com/CIDRAM/CIDRAM/issues/112#issuecomment-493141550 in some way so closing this one.

**Closed by DanielRuf** 2019-05-17 14:02 UTC
